import { LocalConnection } from "../../../../core/client/Connection";
import { RestException } from "../../../../core/exceptions/CoreExceptions";
import { AuthenticateOrSignData, GenericSecuredCertCard, OptionalPin } from "../../Card";
import { DataArrayResponse, DataResponse, T1CResponse } from "../../../../core/service/CoreModel";
import { AbstractEidLUX, AllCertsResponse, BiometricResponse, PictureResponse, SignatureImageResponse } from "./EidLuxModel";
import { AllDataResponse } from "../../pki/luxtrust/LuxTrustModel";
export { EidLux };
declare class EidLux extends GenericSecuredCertCard implements AbstractEidLUX {
    protected url: string;
    protected connection: LocalConnection;
    protected reader_id: string;
    private pin;
    static BIOMETRIC: string;
    static ADDRESS: string;
    static PHOTO: string;
    static SIGNATURE_IMAGE: string;
    constructor(url: string, connection: LocalConnection, reader_id: string, pin: string);
    allDataFilters(): string[];
    allCertFilters(): string[];
    allData(filters: string[], body: OptionalPin, callback?: (error: RestException, data: AllDataResponse) => void | Promise<AllDataResponse>): void | Promise<any>;
    allCerts(filters: string[], body: OptionalPin, callback?: (error: RestException, data: AllCertsResponse) => void | Promise<AllCertsResponse>): void | Promise<any>;
    biometric(body: OptionalPin, callback?: (error: RestException, data: BiometricResponse) => void | Promise<BiometricResponse>): void | Promise<any>;
    picture(body: OptionalPin, callback?: (error: RestException, data: PictureResponse) => void | Promise<PictureResponse>): void | Promise<any>;
    rootCertificate(body: OptionalPin, callback?: (error: RestException, data: DataArrayResponse) => void | Promise<DataArrayResponse>): void | Promise<DataArrayResponse>;
    authenticationCertificate(body: OptionalPin, callback?: (error: RestException, data: DataResponse) => void | Promise<DataResponse>): void | Promise<DataResponse>;
    nonRepudiationCertificate(body: OptionalPin, callback?: (error: RestException, data: DataResponse) => void | Promise<DataResponse>): void | Promise<DataResponse>;
    verifyPin(body: OptionalPin, callback?: (error: RestException, data: T1CResponse) => void | Promise<T1CResponse>): void | Promise<any>;
    signData(body: AuthenticateOrSignData, callback?: (error: RestException, data: DataResponse) => void | Promise<DataResponse>): void | Promise<any>;
    authenticate(body: AuthenticateOrSignData, callback?: (error: RestException, data: DataResponse) => void | Promise<DataResponse>): void | Promise<any>;
    signatureImage(body: OptionalPin, callback?: (error: RestException, data: SignatureImageResponse) => void | Promise<SignatureImageResponse>): void | Promise<any>;
}
